NotificationPortal/NotificationPortal/Controllers/ApplicationController.cs
using NotificationPortal.Models;
using NotificationPortal.Repositories;
using NotificationPortal.ViewModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NotificationPortal.Controllers
{
    [Authorize]
    public class ApplicationController : AppBaseController
    {
        private readonly ApplicationRepo _aRepo = new ApplicationRepo();
        private readonly SelectListRepo _sRepo = new SelectListRepo();

        [HttpGet]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ApplicationIndexVM model = _aRepo.GetApplicationList(sortOrder, currentFilter, searchString, page);
            return View(model);
        }

        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        [HttpGet]
        public ActionResult Create()
        {
            var model = new ApplicationVM
            {
                StatusList = _sRepo.GetStatusList(Key.STATUS_TYPE_APPLICATION),
                ClientList = _sRepo.GetClientList(),
                ServerList = _sRepo.GetServerList(),
            };
            return View(model);
        }

        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ApplicationVM model)
        {
            string msg = "";
            if (ModelState.IsValid)
            {
                bool success = _aRepo.AddApplication(model, out msg);
                if (success)
                {
                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("index");
                }
                else
                {
                    TempData["ErrorMsg"] = msg;
                }
            }
            else
            {
                TempData["ErrorMsg"] = "Application cannot be added at this time.";
            }
            model.StatusList = _sRepo.GetStatusList(Key.STATUS_TYPE_APPLICATION);
            model.ServerList = _sRepo.GetServerList();
            model.ClientList = _sRepo.GetClientList();
            return View(model);
        }

        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        [HttpGet]
        public ActionResult Edit(string id)
        {
            ApplicationVM application = _aRepo.GetApplication(id);
            application.StatusList = _sRepo.GetStatusList(Key.STATUS_TYPE_APPLICATION);
            application.ServerList = _sRepo.GetServerList();
            application.ClientList = _sRepo.GetClientList();
            return View(application);
        }

        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        [HttpPost]
        public ActionResult Edit(ApplicationVM model)
        {
            string msg = "";
            if (ModelState.IsValid)
            {
                bool success = _aRepo.EditApplication(model, out msg);
                if (success)
                {
                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("Details", new { id = model.ReferenceID });
                }
                else
                {
                    TempData["ErrorMsg"] = msg;
                }
            }
            ApplicationVM application = _aRepo.GetApplication(model.ReferenceID);
            application.StatusList = _sRepo.GetStatusList(Key.STATUS_TYPE_APPLICATION);
            application.ClientList = _sRepo.GetClientList();
            application.ServerList = _sRepo.GetServerList();
            return View(application);
        }


        [HttpGet]
        public ActionResult Details(string id)
        {
            return View(_aRepo.GetDetailApplication(id));
        }

        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        [HttpGet]
        public ActionResult Delete(string id)
        {
            return View(_aRepo.GetApplication(id));
        }

        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        [HttpPost]
        public ActionResult Delete(ApplicationVM application)
        {
            string msg = "";
            if (ModelState.IsValid)
            {
                bool success = _aRepo.DeleteApplication(application.ReferenceID, out msg);
                if (success)
                {
                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("index");
                }
                else
                {
                    TempData["ErrorMsg"] = msg;
                }
            }
            else
            {
                TempData["ErrorMsg"] = "Application cannot be deleted at this time.";
            }

            return View(application);
        }
    }
}

NotificationPortal/NotificationPortal/Views/Application/Create.cshtml
@model NotificationPortal.ViewModels.ApplicationVM

@{
    ViewBag.Title = "Add Application";
}


<h1 class="display-4 text-center pb-3">@ViewBag.Title</h1>

<ol class="breadcrumb bg-faded">
    <li class="breadcrumb-item"><a href="~/Dashboard/Index" class="link-color">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="~/Application/Index" class="link-color">Applications</a></li>
    <li class="breadcrumb-item active">@ViewBag.Title</li>
</ol>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal offset-md-3 col-md-6 offset-md-3">
        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger offset-md-3 col-md-6 offset-md-3" })
        @if (TempData["SuccessMsg"] != null)
        {
            <!-- display success message -->
            <p class="alert alert-success alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                @Html.Raw(TempData["SuccessMsg"])
            </p>
        }
        @if (TempData["ErrorMsg"] != null)
        {
            <!-- display error message -->
            <p class="alert alert-danger alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                @Html.Raw(TempData["ErrorMsg"])
            </p>
        }
        <div class="form-group">
            @Html.LabelFor(model => model.ClientRefID, htmlAttributes: new { @class = "" })
            <div>
                @Html.DropDownListFor(m => m.ClientRefID, Model.ClientList, htmlAttributes: new { @class = "form-control", style = "display: none;" })
                @Html.ValidationMessageFor(model => model.ClientRefID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServerReferenceIDs, htmlAttributes: new { @class = "" })
            <div>
                @Html.ListBoxFor(m => m.ServerReferenceIDs, Model.ServerList, htmlAttributes: new { @class = "form-control", style = "display: none;" })
                @Html.ValidationMessageFor(model => model.ServerReferenceIDs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationName, htmlAttributes: new { @class = "required" })
            @Html.EditorFor(model => model.ApplicationName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ApplicationName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "required" })
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "required" })
            @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusID, htmlAttributes: new { @class = "" })
            @Html.DropDownListFor(m => m.StatusID, Model.StatusList, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-success" />
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
        </div>
    </div>
}

<script src="~/Scripts/Custom/application-multiselect.js" type="text/javascript"></script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NotificationPortal/NotificationPortal/Views/Application/Delete.cshtml
@model NotificationPortal.ViewModels.ApplicationVM

@{
    ViewBag.Title = "Delete";
}

<h1 class="text-center display-4 pb-3">@ViewBag.Title - @Model.ApplicationName</h1>

<ol class="breadcrumb bg-faded">
    <li class="breadcrumb-item"><a href="~/Dashboard/Index" class="link-color">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="~/Application/Index" class="link-color">Applications</a></li>
    <li class="breadcrumb-item active">@Html.DisplayFor(model => model.ApplicationName)</li>
</ol>


<div class="container">
    <h4 class="text-danger pb-2">Are you sure you want to delete this?</h4>

    @if (TempData["SuccessMsg"] != null)
    {
            <!-- display success message -->
        <p class="alert alert-success alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            @Html.Raw(TempData["SuccessMsg"])
        </p>
    }
    @if (TempData["ErrorMsg"] != null)
    {
            <!-- display error message -->
        <p class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            @Html.Raw(TempData["ErrorMsg"])
        </p>
    }

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#Applications" role="tab">Application</a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active" id="User" role="tabpanel">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ApplicationName)
                    </dt>

                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ApplicationName)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Description)
                    </dt>

                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.URL)
                    </dt>

                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.URL)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.StatusName)
                    </dt>

                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.StatusName)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ClientName)
                    </dt>

                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ClientName)
                    </dd>

                </dl>
            </div>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.ReferenceID)
            @Html.HiddenFor(model => model.ApplicationName)
            @Html.HiddenFor(model => model.ClientRefID)
            @Html.HiddenFor(model => model.Description)
            @Html.HiddenFor(model => model.URL)
            @Html.HiddenFor(model => model.StatusID)
            @Html.HiddenFor(model => model.ClientName)
            @Html.HiddenFor(model => model.ClientRefID)

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-mint text-white" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
            </div>
        }
</div>

NotificationPortal/NotificationPortal/Views/Application/Edit.cshtml
@model NotificationPortal.ViewModels.ApplicationVM

@{
    ViewBag.Title = "Edit Application";
}

@{
  var className = Model.StatusName == "Offline" ? "badge badge-danger" : "badge badge-success";
}

<h1 class="text-center display-4 pb-3">@ViewBag.Title - @Model.ApplicationName <span class="@className">@Html.DisplayFor(modelItem => Model.StatusName)</span></h1>

<ol class="breadcrumb bg-faded">
    <li class="breadcrumb-item"><a href="~/Dashboard/Index" class="link-color">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="~/Application/Index" class="link-color">Applications</a></li>
    <li class="breadcrumb-item active">@Html.DisplayFor(model => model.ApplicationName)</li>
</ol>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (TempData["SuccessMsg"] != null)
        {
            <!-- display success message -->
            <p class="alert alert-success alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                @Html.Raw(TempData["SuccessMsg"])
            </p>
        }
        @if (TempData["ErrorMsg"] != null)
        {
            <!-- display error message -->
            <p class="alert alert-danger alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                @Html.Raw(TempData["ErrorMsg"])
            </p>
        }
        @Html.HiddenFor(model => model.ReferenceID)

        <div class="form-group">
            @Html.LabelFor(model => model.ClientRefID, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.DropDownListFor(m => m.ClientRefID, Model.ClientList as SelectList, htmlAttributes: new { @class = "form-control", style = "display: none;" })
                @Html.ValidationMessageFor(model => model.ClientRefID, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServerReferenceIDs, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.ListBoxFor(m => m.ServerReferenceIDs, Model.ServerList, htmlAttributes: new { @class = "form-control", style = "display: none;" })
                @Html.ValidationMessageFor(model => model.ServerReferenceIDs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationName, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.EditorFor(model => model.ApplicationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusID, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.DropDownListFor(m => m.StatusID, Model.StatusList as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="offset-md-3 col-md-6">
                <input type="submit" value="Save" class="btn btn-mint text-white" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

<script src="~/Scripts/Custom/application-multiselect.js" type="text/javascript"></script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NotificationPortal/NotificationPortal/Views/Application/Index.cshtml
@model NotificationPortal.ViewModels.ApplicationIndexVM
@using PagedList.Mvc;

@{
    ViewBag.Title = "Applications";
}

<h1 class="text-center display-4 pb-3">@ViewBag.Title</h1>
<!-- ========================= breadcrumb ========================= -->
<ol class="breadcrumb bg-faded">
    <li class="breadcrumb-item"><a href="~/Dashboard/Index" class="link-color">Dashboard</a></li>
    <li class="breadcrumb-item active">@ViewBag.Title</li>
</ol>
@if (TempData["SuccessMsg"] != null)
{
            <!-- display success message -->
    <p class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Html.Raw(TempData["SuccessMsg"])
    </p>
}
@if (TempData["ErrorMsg"] != null)
{
            <!-- display error message -->
    <p class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Html.Raw(TempData["ErrorMsg"])
    </p>
}
<!-- ========================= search & create ========================= -->
<div class="row">
    <div class="form-inline col-sm-8 col-xs-12 pb-3">
        @using (Html.BeginForm("Index", "Application", FormMethod.Get, new { @class = "form-inline search pb-3" }))
        {
            @Html.TextBox("SearchString", Model.CurrentFilter, new { @class = "form-control mr-sm-2" })

            <span class="hidden-xs-down">
                <input class="btn btn-secondary" type="submit" value="Search" />
            </span>

            <span class="hidden-sm-up">
                <button id="hidden-search">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </button>
            </span>
        }
    </div>

    @if (Request.IsAuthenticated && User.IsInRole("Admin") || (Request.IsAuthenticated && User.IsInRole("Staff")))
    {

        <div class="offset-sm-2 col-sm-2 col-xs-12">
            <div class="float-create">
                @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-mint text-white" })
            </div>
        </div>
    }
</div>

@if (Model.Applications.Count() > 0)
{
    <table class="table table-bordered">
        @{
            var filterAppByNameAsce = "";
            var filterAppByNameDesc = "";
            var filterAppByDescriptionAsce = "";
            var filterAppByDescriptionDesc = "";
            var filterAppByUrlAsce = "";
            var filterAppByUrlDesc = "";
            var filterByClientAsce = "";
            var filterByClientDesc = "";
            var filterByStatusAsce = "";
            var filterByStatusDesc = "";

            if (Model.CurrentSort != null)
            {
                filterAppByNameAsce = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_APP_BY_NAME_ASCE) ? "active-arrow" : "disabled-arrow";
                filterAppByNameDesc = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_APP_BY_NAME_DESC) ? "active-arrow" : "disabled-arrow";
                filterAppByDescriptionAsce = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_APP_BY_DESCRIPTION_ASCE) ? "active-arrow" : "disabled-arrow";
                filterAppByDescriptionDesc = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_APP_BY_DESCRIPTION_DESC) ? "active-arrow" : "disabled-arrow";
                filterAppByUrlAsce = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_APP_BY_URL_ASCE) ? "active-arrow" : "disabled-arrow";
                filterAppByUrlDesc = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_APP_BY_URL_DESC) ? "active-arrow" : "disabled-arrow";
                filterByClientAsce = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_APP_BY_CLIENT_ASCE) ? "active-arrow" : "disabled-arrow";
                filterByClientDesc = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_APP_BY_CLIENT_DESC) ? "active-arrow" : "disabled-arrow";
                filterByStatusAsce = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_STATUS_BY_NAME_ASCE) ? "active-arrow" : "disabled-arrow";
                filterByStatusDesc = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_STATUS_BY_NAME_DESC) ? "active-arrow" : "disabled-arrow";
            }
        }

        <thead>
            <tr class="bg-inverse text-white">
                <th>
                    <a href="@Url.Action("Index", "Application", new {sortOrder = Model.ApplicationSort, currentFilter = Model.CurrentFilter})">
                        Application
                        <span class="filter-arrows">
                            <i class="fa fa-caret-up @filterAppByNameAsce" aria-hidden="true"></i>
                            <i class="fa fa-caret-down @filterAppByNameDesc" aria-hidden="true"></i>
                        </span>
                    </a>
                </th>
                <th>
                    <a href="@Url.Action("Index", "Application", new {sortOrder = Model.DescriptionSort, currentFilter = Model.CurrentFilter})">
                        Description
                        <span class="filter-arrows">
                            <i class="fa fa-caret-up @filterAppByDescriptionAsce" aria-hidden="true"></i>
                            <i class="fa fa-caret-down @filterAppByDescriptionDesc" aria-hidden="true"></i>
                        </span>
                    </a>
                </th>
                <th>
                    <a href="@Url.Action("Index", "Application", new {sortOrder = Model.URLSort, currentFilter = Model.CurrentFilter})">
                        URL
                        <span class="filter-arrows">
                            <i class="fa fa-caret-up @filterAppByUrlAsce" aria-hidden="true"></i>
                            <i class="fa fa-caret-down @filterAppByUrlDesc" aria-hidden="true"></i>
                        </span>
                    </a>
                </th>
                <th>
                    <a href="@Url.Action("Index", "Application", new {sortOrder = Model.ClientSort, currentFilter = Model.CurrentFilter})">
                        Client Name
                        <span class="filter-arrows">
                            <i class="fa fa-caret-up @filterByClientAsce" aria-hidden="true"></i>
                            <i class="fa fa-caret-down @filterByClientDesc" aria-hidden="true"></i>
                        </span>
                    </a>
                </th>
                <th>
                    <a href="@Url.Action("Index", "Application", new {sortOrder = Model.StatusSort, currentFilter = Model.CurrentFilter})">
                        Status
                        <span class="filter-arrows">
                            <i class="fa fa-caret-up @filterByStatusAsce" aria-hidden="true"></i>
                            <i class="fa fa-caret-down @filterByStatusDesc" aria-hidden="true"></i>
                        </span>
                    </a>
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Applications)
            {
                var statusClass = item.StatusName.ToUpper() == NotificationPortal.Models.Key.STATUS_APPLICATION_OFFLINE.ToUpper() ? "badge badge-danger" : "badge badge-success";

                <tr class="clickable-row" id="@item.ReferenceID" data-href="Application/Details/@item.ReferenceID">
                    <td data-title="Application" class="first-row">
                        @Html.DisplayFor(modelItem => item.ApplicationName)
                    </td>
                    <td data-title="Description">
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td data-title="URL">
                        @Html.DisplayFor(modelItem => item.URL)
                    </td>
                    <td data-title="Client">
                        @Html.DisplayFor(modelItem => item.ClientName)
                    </td>
                    <td data-title="Status">
                        <span class="current-status @statusClass">
                            @Html.DisplayFor(modelItem => item.StatusName)
                        </span>
                        <i class="preloader fa fa-spinner fa-spin" style="display:none"></i>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    if (Model.TotalItemCount > NotificationPortal.Repositories.ConstantsRepo.PAGE_SIZE)
    {
        <!-- ========================= pagination ========================= -->
        <!-- hide pagination if only 1 page -->
        @Html.PagedListPager(Model.Applications, page => Url.Action("Index",
        new { page, sortOrder = Model.CurrentSort, currentFilter = Model.CurrentFilter }))
    }
    <div class="pageinfo-display">
        <p>Displaying @Model.ItemStart - @Model.ItemEnd of @Model.TotalItemCount item(s)</p>
    </div>
}
else
{
    if (Model == null)
    {
        <p> Something went wrong, application database not available.</p>
    }
    else
    {
        <p> There are no such applications in the database at the moment.</p>
    }

}
<div class="hidden-menu">
    <ul>
        <li><a href="Application/Edit/" class="btn btn-sm">Edit</a></li>
        <li><a href="Application/Delete/" class="btn btn-sm">Delete</a></li>
    </ul>
</div>

<script src="~/Scripts/Custom/refresh-application-status.js"></script>