NotificationPortal/NotificationPortal/Controllers/ServerController.cs
using NotificationPortal.Models;
using NotificationPortal.Repositories;
using NotificationPortal.ViewModels;
using System.Web.Mvc;


namespace NotificationPortal.Controllers
{
    [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
    public class ServerController : AppBaseController
    {
        private readonly ServerRepo _serverRepo = new ServerRepo();
        private readonly SelectListRepo _selectRepo = new SelectListRepo();

        [HttpGet]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ServerIndexVM model = _serverRepo.GetServerList(sortOrder, currentFilter, searchString, page);
            return View(model);
        }
        //Get Create new Server
        [HttpGet]
        public ActionResult Create()
        {
            // To be modified: global method for status in development
            var model = new ServerVM
            {
                StatusList = _serverRepo.GetStatusList(),
                LocationList = _serverRepo.GetLocationList(),
                ServerTypeList = _serverRepo.GetServerTypeList(),
                ApplicationList = _selectRepo.GetApplicationList()
            };

            return View(model);
        }
        //Post Create new server 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ServerVM model)
        {
            if (ModelState.IsValid)
            {
                if (_serverRepo.AddServer(model, out string msg))
                {
                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("Index");
                }

                TempData["ErrorMsg"] = msg;
            }

            model.StatusList = _serverRepo.GetStatusList();
            model.LocationList = _serverRepo.GetLocationList();
            model.ServerTypeList = _serverRepo.GetServerTypeList();
            model.ApplicationList = _selectRepo.GetApplicationList();

            return View(model);
        }
        //Get Edit Server
        [HttpGet]
        public ActionResult Edit(string id)
        {
            var server = _serverRepo.GetServerDetails(id);

            // To be modified: global method for status in development
            if (server == null)
            {
                TempData["ErrorMsg"] = "Cannot edit this server at this time";
                return RedirectToAction("Index");
            }

            return View(server);
        }
        //Post Edit server
        [HttpPost]
        public ActionResult Edit(ServerDetailVM model)
        {
            if (ModelState.IsValid)
            {
                if (_serverRepo.EditServer(model, out string msg))
                {
                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("Index");
                }

                TempData["ErrorMsg"] = msg;
            }

            model.StatusList = _serverRepo.GetStatusList();
            model.LocationList = _serverRepo.GetLocationList();
            model.ServerTypeList = _serverRepo.GetServerTypeList();
            model.ApplicationList = _selectRepo.GetApplicationList();

            return View(model);
        }
        //Get Server Detials
        [HttpGet]
        public ActionResult Details(string id)
        {
            var server = _serverRepo.GetServerDetails(id);

            if(server == null)
            {
                TempData["ErrorMsg"] = "Cannot get this server at this time";
                return RedirectToAction("Index");
            }

            return View(server);
        }
        //Post Server Delete
        [HttpGet]
        public ActionResult Delete(string id)
        {
            var server = _serverRepo.GetDeleteServer(id);

            if (server == null)
            {
                TempData["ErrorMsg"] = "Cannot delete this server at this time";
                return RedirectToAction("Index");
            }

            return View(server);
        }
        //Post Delete Server
        [HttpPost]
        public ActionResult Delete(ServerDeleteVM server)
        {
            if (ModelState.IsValid)
            {
                if (_serverRepo.DeleteServer(server.ReferenceID, out string msg))
                {
                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("Index");
                }

                TempData["ErrorMsg"] = msg;
            }

            return View(server);
        }
    }
}

NotificationPortal/NotificationPortal/Views/Server/Create.cshtml
@model NotificationPortal.ViewModels.ServerVM

@{
    ViewBag.Title = "Add Server";
}

<h1 class="display-4 text-center pb-3">@ViewBag.Title</h1>

<ol class="breadcrumb bg-faded">
    <li class="breadcrumb-item"><a href="~/Dashboard/Index" class="link-color">Home</a></li>
    <li class="breadcrumb-item"><a href="~/Server/Index" class="link-color">Servers</a></li>
    <li class="breadcrumb-item active">@ViewBag.Title</li>
</ol>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="offset-md-3 col-md-6 offset-md-3">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @if (TempData["SuccessMsg"] != null)
            {
            <!-- display success message -->
                <p class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    @Html.Raw(TempData["SuccessMsg"])
                </p>
            }
            @if (TempData["ErrorMsg"] != null)
            {
            <!-- display error message -->
                <p class="alert alert-danger alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    @Html.Raw(TempData["ErrorMsg"])
                </p>
            }
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServerName, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.EditorFor(model => model.ServerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationReferenceIDs, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                <i id="preloader" class="fa fa-spinner fa-spin" style="display: none;"></i>
                <div id="ApplicationList">
                    @Html.ListBoxFor(m => m.ApplicationReferenceIDs, Model.ApplicationList as SelectList, htmlAttributes: new { style = "display: none;" })
                    @Html.ValidationMessageFor(model => model.ApplicationReferenceIDs, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.DropDownListFor(m => m.LocationID, Model.LocationList, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StatusID, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.DropDownListFor(m => m.StatusID, Model.StatusList, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServerTypeID, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.DropDownListFor(m => m.ServerTypeID, Model.ServerTypeList, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="offset-md-3 col-md-6">
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
                }

<script src="~/Scripts/Custom/server-multiselect.js" type="text/javascript"></script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NotificationPortal/NotificationPortal/Views/Server/Delete.cshtml
@model NotificationPortal.ViewModels.ServerDeleteVM

@{
    ViewBag.Title = "Delete";
}

@{
    var className = Model.StatusName == "Offline" ? "badge badge-danger" : "badge badge-success";
}

<h1 class="text-center display-4 pb-3">@ViewBag.Title - @Model.ServerName <span class="@className">@Html.DisplayFor(modelItem => Model.StatusName)</span></h1>

<ol class="breadcrumb bg-faded">
    <li class="breadcrumb-item"><a href="~/Dashboard/Index" class="link-color">Home</a></li>
    <li class="breadcrumb-item"><a href="~/Server/Index">Servers</a></li>
    <li class="breadcrumb-item active">@Html.DisplayFor(model => model.ServerName)</li>
</ol>

<h4 class="text-danger pb-2">Are you sure you want to delete this server?</h4>

@if (TempData["SuccessMsg"] != null)
{
            <!-- display success message -->
    <p class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Html.Raw(TempData["SuccessMsg"])
    </p>
}
@if (TempData["ErrorMsg"] != null)
{
            <!-- display error message -->
    <p class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Html.Raw(TempData["ErrorMsg"])
    </p>
}

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ServerName)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ServerName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ServerTypeName)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ServerTypeName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusName)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StatusName)
        </dd>

    </dl>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ReferenceID)
        @Html.HiddenFor(model => model.Location)
        @Html.HiddenFor(model => model.Description)
        @Html.HiddenFor(model => model.StatusName)
        @Html.HiddenFor(model => model.ServerName)
        @Html.HiddenFor(model => model.ServerTypeName)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-mint text-white" />
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
        </div>
    }
</div>

NotificationPortal/NotificationPortal/Views/Server/Edit.cshtml
@model NotificationPortal.ViewModels.ServerDetailVM

@{
    ViewBag.Title = "Edit Server";
}

@{
    var className = Model.Status == "Offline" ? "badge badge-danger" : "badge badge-success";
}

<h1 class="text-center display-4 pb-3">@ViewBag.Title - @Model.ServerName <span class="@className">@Html.DisplayFor(modelItem => Model.Status)</span></h1>


<ol class="breadcrumb bg-faded">
    <li class="breadcrumb-item"><a href="~/Dashboard/Index" class="link-color">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="~/Server/Index" class="link-color">Servers</a></li>
    <li class="breadcrumb-item active">@Html.DisplayFor(model => model.ServerName)</li>
</ol>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="offset-md-3 col-md-6 offset-md-3">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @if (TempData["SuccessMsg"] != null)
            {
            <!-- display success message -->
                <p class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    @Html.Raw(TempData["SuccessMsg"])
                </p>
            }
            @if (TempData["ErrorMsg"] != null)
            {
            <!-- display error message -->
                <p class="alert alert-danger alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    @Html.Raw(TempData["ErrorMsg"])
                </p>
            }
        </div>

        @Html.HiddenFor(model => model.ReferenceID)

        <div class="form-group">
            @Html.LabelFor(model => model.ServerName, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.EditorFor(model => model.ServerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationReferenceIDs, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                <i id="preloader" class="fa fa-spinner fa-spin" style="display: none;"></i>
                <div id="ApplicationList">
                    @Html.ListBoxFor(m => m.ApplicationReferenceIDs, Model.ApplicationList as SelectList, htmlAttributes: new { style = "display: none;" })
                    @Html.ValidationMessageFor(model => model.ApplicationReferenceIDs, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.DropDownListFor(m => m.LocationID, Model.LocationList as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusID, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.DropDownListFor(m => m.StatusID, Model.StatusList as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServerTypeID, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.DropDownListFor(m => m.ServerTypeID, Model.ServerTypeList as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServerTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label offset-md-3 col-md-2 required" })
            <div class="offset-md-3 col-md-6 offset-md-3">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="offset-md-3 col-md-6">
                <input type="submit" value="Save" class="btn btn-success" />
                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
                }

<script src="~/Scripts/Custom/server-multiselect.js" type="text/javascript"></script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NotificationPortal/NotificationPortal/Views/Server/Index.cshtml
@model NotificationPortal.ViewModels.ServerIndexVM
@using PagedList.Mvc;

@{
    ViewBag.Title = "Servers";
}

<h1 class="text-center display-4 pb-3">@ViewBag.Title</h1>

<ol class="breadcrumb bg-faded">
    <li class="breadcrumb-item"><a href="~/Dashboard/Index" class="link-color">Dashboard</a></li>
    <li class="breadcrumb-item active">@ViewBag.Title</li>
</ol>
@if (TempData["SuccessMsg"] != null)
{
            <!-- display success message -->
    <p class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Html.Raw(TempData["SuccessMsg"])
    </p>
}
@if (TempData["ErrorMsg"] != null)
{
            <!-- display error message -->
    <p class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Html.Raw(TempData["ErrorMsg"])
    </p>
}
<div class="row">
    <div class="form-inline col-sm-8 col-xs-12 pb-3">
        @using (Html.BeginForm("Index", "Server", FormMethod.Get, new { @class = "form-inline search pb-3" }))
        {
            @Html.TextBox("SearchString", Model.CurrentFilter, new { @class = "form-control mr-sm-2" })

            <span class="hidden-xs-down">
                <input class="btn btn-secondary" type="submit" value="Search" />
            </span>

            <span class="hidden-sm-up">
                <button id="hidden-search">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </button>
            </span>
        }
    </div>

    <div class="offset-sm-2 col-sm-2 col-xs-12">
        <div class="float-create">
            @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-mint text-white" })
        </div>
    </div>
</div>

@if (Model.Servers.Count() > 0)
{
    <table class="table table-bordered">
        @{
            var filterByServerNameAsce = "";
            var filterByServerNameDesc = "";
            var filterByDescriptionAsce = "";
            var filterByDescriptionDesc = "";
            var filterByLocationAsce = "";
            var filterByLocationDesc = "";
            var filterByServerTypeAsce = "";
            var filterByServerTypeDesc = "";
            var filterByStatusAsce = "";
            var filterByStatusDesc = "";

            if (Model.CurrentSort != null)
            {
                filterByServerNameAsce = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_SERVER_BY_NAME_ASCE) ? "active-arrow" : "disabled-arrow";
                filterByServerNameDesc = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_SERVER_BY_NAME_DESC) ? "active-arrow" : "disabled-arrow";

                filterByDescriptionAsce = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_SERVER_BY_DESCRIPTION_ASCE) ? "active-arrow" : "disabled-arrow";
                filterByDescriptionDesc = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_SERVER_BY_DESCRIPTION_DESC) ? "active-arrow" : "disabled-arrow";

                filterByLocationAsce = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_SERVER_BY_LOCATION_NAME_ASCE) ? "active-arrow" : "disabled-arrow";
                filterByLocationDesc = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_SERVER_BY_LOCATION_NAME_DESC) ? "active-arrow" : "disabled-arrow";

                filterByServerTypeAsce = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_SERVERTYPE_BY_NAME_ASCE) ? "active-arrow" : "disabled-arrow";
                filterByServerTypeDesc = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_SERVERTYPE_BY_NAME_DESC) ? "active-arrow" : "disabled-arrow";

                filterByStatusAsce = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_SERVER_BY_STATUS_NAME_ASCE) ? "active-arrow" : "disabled-arrow";
                filterByStatusDesc = Model.CurrentSort.Contains(NotificationPortal.Repositories.ConstantsRepo.SORT_SERVER_BY_STATUS_NAME_DESC) ? "active-arrow" : "disabled-arrow";
            }
        }

        <thead>
            <tr class="bg-inverse text-white">
                <th>
                    <a href="@Url.Action("Index", "Server", new { sortOrder = Model.ServerNameSort, currentFilter = Model.CurrentFilter })">
                        Server
                        <span class="filter-arrows">
                            <i class="fa fa-caret-up @filterByServerNameAsce" aria-hidden="true"></i>
                            <i class="fa fa-caret-down @filterByServerNameDesc" aria-hidden="true"></i>
                        </span>
                    </a>
                </th>
                <th>
                    <a href="@Url.Action("Index", "Server", new { sortOrder = Model.ServerTypeSort, currentFilter = Model.CurrentFilter })">
                        Server Type
                        <span class="filter-arrows">
                            <i class="fa fa-caret-up @filterByServerTypeAsce" aria-hidden="true"></i>
                            <i class="fa fa-caret-down @filterByServerTypeDesc" aria-hidden="true"></i>
                        </span>
                    </a>
                </th>
                <th>
                    <a href="@Url.Action("Index", "Server", new { sortOrder = Model.DescriptionSort, currentFilter = Model.CurrentFilter })">
                        Description
                        <span class="filter-arrows">
                            <i class="fa fa-caret-up @filterByDescriptionAsce" aria-hidden="true"></i>
                            <i class="fa fa-caret-down @filterByDescriptionDesc" aria-hidden="true"></i>
                        </span>
                    </a>
                </th>
                <th>
                    <a href="@Url.Action("Index", "Server", new { sortOrder = Model.LocationSort, currentFilter = Model.CurrentFilter })">
                        Location
                        <span class="filter-arrows">
                            <i class="fa fa-caret-up @filterByLocationAsce" aria-hidden="true"></i>
                            <i class="fa fa-caret-down @filterByLocationDesc" aria-hidden="true"></i>
                        </span>
                    </a>
                </th>
                <th>
                    <a href="@Url.Action("Index", "Server", new { sortOrder = Model.StatusSort, currentFilter = Model.CurrentFilter })">
                        Status
                        <span class="filter-arrows">
                            <i class="fa fa-caret-up @filterByStatusAsce" aria-hidden="true"></i>
                            <i class="fa fa-caret-down @filterByStatusDesc" aria-hidden="true"></i>
                        </span>
                    </a>
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Servers)
            {
                var statusClass = item.StatusName.ToUpper() == NotificationPortal.Models.Key.STATUS_SERVER_OFFLINE.ToUpper() ? "badge badge-danger" : "badge badge-success";
                var statusIcon = item.StatusName.ToUpper() == NotificationPortal.Models.Key.STATUS_SERVER_ONLINE.ToUpper() ? "<i class='fa fa-check text-success' aria-hidden='true'></i>" : "<i class='fa fa-times text-danger' aria-hidden='true'></i>";

                <tr class="clickable-row" id="@item.ReferenceID" data-href="Server/Details/@item.ReferenceID">
                    <td data-title="Server" class="first-row">
                        @Html.DisplayFor(modelItem => item.ServerName)
                    </td>
                    <td data-title="Server" Type>
                        @Html.DisplayFor(modelItem => item.ServerTypeName)
                    </td>
                    <td data-title="Description">
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td data-title="Location">
                        @Html.DisplayFor(modelItem => item.LocationName)
                    </td>
                    <td data-title="Status">
                        <span>@Html.Raw(statusIcon)</span>
                        <span class="@statusClass">
                            @Html.DisplayFor(modelItem => item.StatusName)
                        </span>
                    </td>
                </tr>
          }
        </tbody>       
    </table>

   <!-- ========================= pagination ========================= -->
    if (Model.TotalItemCount > NotificationPortal.Repositories.ConstantsRepo.PAGE_SIZE)
    {
        <!-- hide pagination if only 1 page -->
        @Html.PagedListPager(Model.Servers, page => Url.Action("Index",
        new { page, sortOrder = Model.CurrentSort, currentFilter = Model.CurrentFilter }))
    }

    <div class="pageinfo-display">
        <p>Displaying @Model.ItemStart - @Model.ItemEnd of @Model.TotalItemCount item(s)</p>
    </div>
}
else
{
    if (Model == null)
    {
        <p> Something went wrong, cannot retrieve information.</p>
    }
    else
    {
        <p>There are no such servers in the database at the moment.</p>
    }

}

<div class="hidden-menu">
    <ul>
        <li><a href="Server/Edit/" class="btn btn-sm">Edit</a></li>
        <li><a href="Server/Delete/" class="btn btn-sm">Delete</a></li>
    </ul>
</div>