NotificationPortal/NotificationPortal/Controllers/NotificationController.cs
using NotificationPortal.Models;
using NotificationPortal.Repositories;
using NotificationPortal.Service;
using NotificationPortal.ViewModels;
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace NotificationPortal.Controllers
{
    [Authorize]
    public class NotificationController : AppBaseController
    {
        private readonly NotificationRepo _nRepo = new NotificationRepo();

        [HttpGet]
        public ActionResult Index()
        {
            NotificationIndexVM model;
            model = _nRepo.CreateIndexModel();
            return View(model);
        }

        [HttpGet]
        public ActionResult DetailsThread(string id)
        {
            var model = _nRepo.CreateDetailModel(id);
            if (model == null)
            {
                TempData["ErrorMsg"] = "Cannot display this thread at the moment";
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        public ActionResult CreateThread()
        {
            var model = _nRepo.CreateAddModel();
            if (model == null)
            {
                TempData["ErrorMsg"] = "Cannot create new thread at the moment";
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        public async Task<ActionResult> CreateThread(NotificationCreateVM model) {
            string result = "";
            if (ModelState.IsValid)
            {
                // give this model a new incident #
                model.IncidentNumber = _nRepo.NewIncidentNumber(model.NotificationTypeID);
                // add notification to the database
                bool success = _nRepo.CreateNotification(model, out result);
                if (success)
                {
                    // send email and sms after notification has been created
                    await NotificationService.SendEmail(_nRepo.CreateMails(model));
                    await NotificationService.SendSMS(_nRepo.GetPhoneNumbers(model), TemplateService.NotificationSMS(model));

                    TempData["SuccessMsg"] = result;
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["ErrorMsg"] = "Cannot add Notification, model not valid.";
            }

            // recreate model for the view
            model = _nRepo.CreateAddModel(model);
            // if notification returns null, redirect to notification index
            if (model == null)
            {
                TempData["ErrorMsg"] = "Cannot create new thread at the moment";
                return RedirectToAction("Index");
            }

            TempData["ErrorMsg"] = result;
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        public ActionResult Create(string id)
        {
            var model = _nRepo.CreateUpdateModel(id);
            if (model == null)
            {
                TempData["ErrorMsg"] = "Cannot new notification at the moment";
                return RedirectToAction("DetailsThread", new { id = id });
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        public async Task<ActionResult> Create(NotificationCreateVM model)
        {
            string result = "";
            if (ModelState.IsValid)
            {
                // add notification to the database
                bool success = _nRepo.CreateNotification(model, out result);
                if (success)
                {
                    // send email and sms after notification has been created
                    await NotificationService.SendEmail(_nRepo.CreateMails(model));
                    await NotificationService.SendSMS(_nRepo.GetPhoneNumbers(model), TemplateService.NotificationSMS(model));

                    TempData["SuccessMsg"] = result;
                    return RedirectToAction("DetailsThread",new { id = model.IncidentNumber });
                }
            }
            else
            {
                TempData["ErrorMsg"] = "Cannot update Notification, model not valid.";
            }

            // recreate model for the view
            model = _nRepo.CreateUpdateModel(model.IncidentNumber, model);
            // if notification returns null, redirect to thread view
            if (model == null)
            {
                TempData["ErrorMsg"] = "Cannot create new notification at the moment";
                return RedirectToAction("DetailsThread", new { id = model.IncidentNumber });
            }

            TempData["ErrorMsg"] = result;
            return View(model);
        }
        
        [HttpGet]
        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        public ActionResult Edit(string id)
        {
            var model = _nRepo.CreateEditModel(id);
            if (model == null)
            {
                TempData["ErrorMsg"] = "Cannot edit this notification at the moment";
                return RedirectToAction("DetailsThread", new { id = id });
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = Key.ROLE_ADMIN + "," + Key.ROLE_STAFF)]
        public ActionResult Edit(NotificationEditVM model)
        {
            string result = "";
            if (ModelState.IsValid)
            {
                bool success = _nRepo.EditNotification(model, out result);
                if (success)
                {
                    TempData["SuccessMsg"] = result;
                    return RedirectToAction("DetailsThread", new { id = model.IncidentNumber });
                }
            }
            else
            {
                TempData["ErrorMsg"] = "Cannot edit Notification, model not valid.";
            }

            // recreate model for the view
            model = _nRepo.CreateEditModel(model.NotificationReferenceID, model);
            // if notification returns null, redirect to thread view
            if (model == null)
            {
                TempData["ErrorMsg"] = "Cannot create new notification at the moment";
                return RedirectToAction("DetailsThread", new { id = model.IncidentNumber });
            }

            TempData["ErrorMsg"] = result;
            return View(model);
        }
        
        [HttpGet]
        [Authorize(Roles = Key.ROLE_ADMIN)]
        public ActionResult Delete(string id)
        {
            var model = _nRepo.CreateDeleteModel(id);
            if (model == null)
            {
                TempData["ErrorMsg"] = "Cannot delete this notification at the moment";
                return RedirectToAction("DetailsThread",new { id = id });
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = Key.ROLE_ADMIN)]
        public ActionResult Delete(NotificationDetailVM model)
        {
            string result = "";
            if (ModelState.IsValid)
            {
                bool success = _nRepo.DeleteNotification(model.ReferenceID, out result);
                if (success)
                {
                    TempData["SuccessMsg"] = result;
                    // handle when thread no longer exists
                    bool emptyThread = _nRepo.CheckEmptyThread(model.IncidentNumber);
                    if (emptyThread)
                    {
                        return RedirectToAction("Index");
                    }
                    return RedirectToAction("DetailsThread", new { id = model.IncidentNumber });
                }
            }
            else
            {
                TempData["ErrorMsg"] = "Cannot delete Notification, try again later.";
            }

            // recreate the model for the view
            model = _nRepo.CreateDeleteModel(model.ReferenceID);
            // if notification returns null, redirect to thread view
            if (model == null)
            {
                TempData["ErrorMsg"] = "Cannot delete this notification at the moment";
                return RedirectToAction("DetailsThread", new { id = model.IncidentNumber });
            }

            TempData["ErrorMsg"] = result;
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = Key.ROLE_ADMIN)]
        public ActionResult DeleteThread(string id)
        {
            var model = _nRepo.CreateDetailModel(id);
            if (model==null)
            {
                TempData["ErrorMsg"] = "Cannot delete this thread at the moment";
                return RedirectToAction("DetailsThread", new { id = id });
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = Key.ROLE_ADMIN)]
        public ActionResult DeleteThread(ThreadDetailVM model)
        {
            string result = "";
            if (ModelState.IsValid)
            {
                bool success = _nRepo.DeleteThread(model.IncidentNumber, out result);
                if (success)
                {
                    TempData["SuccessMsg"] = result;
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ViewBag.ErrorMsg = "Cannot add Notification, model not valid.";
            }

            // recreate the model for the view
            model = _nRepo.CreateDetailModel(model.IncidentNumber);
            // if notification returns null, redirect to notification index
            if (model == null)
            {
                TempData["ErrorMsg"] = "Cannot delete this thread at the moment";

NotificationPortal/NotificationPortal/Views/Notification/Add.cshtml
@model NotificationPortal.ViewModels.NotificationCreateVM

@{
    ViewBag.Title = "Add Notification";
}

<h1 class="display-4 text-center pb-3">@ViewBag.Title</h1>

<ol class="breadcrumb bg-faded">
    <li class="breadcrumb-item"><a href="~/Dashboard/Index" class="link-color">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="~/Notification/Index" class="link-color">Notifications</a></li>
    <li class="breadcrumb-item active">Add Notification</li>
</ol>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <!--notification server ID-->
        <div class="form-group">
            @Html.LabelFor(model => model.ServerReferenceIDs, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-12">
                @Html.ListBoxFor(m => m.ServerReferenceIDs, Model.ServerList, htmlAttributes: new { @id = "ServerList", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServerReferenceIDs, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--notification application ID-->
        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationReferenceIDs, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-12">
                <select class="form-control valid" id="ApplicationReferenceIDs" name="ApplicationReferenceIDs" multiple="multiple" aria-invalid="false">
                    @foreach (var item in Model.ApplicationList)
                    {
                        <option value="@Html.DisplayFor(modelItem => item.ReferenceID)" class="ApplicationListItem @Html.DisplayFor(modelItem => item.ServerReferenceIDs)">@Html.DisplayFor(modelItem => item.ApplicationName)</option>

                    }
                </select>
               @* @Html.ListBoxFor(m => m.ApplicationReferenceIDs, Model.ApplicationList, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.ApplicationReferenceIDs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <!--notification type-->
            <div class="form-group col-md-3">
                @Html.LabelFor(model => model.NotificationTypeList, htmlAttributes: new { @class = "control-label" })
                <div class="col-md-12">
                    @Html.DropDownListFor(m => m.NotificationTypeID, Model.NotificationTypeList, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>

            <!--level of impact-->
            <div class="form-group col-md-3">
                @Html.LabelFor(model => model.LevelOfImpactList, htmlAttributes: new { @class = "control-label" })
                <div class="col-md-12">
                    @Html.DropDownListFor(m => m.LevelOfImpactID, Model.LevelOfImpactList, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>

            <!--notification status-->
            <div class="form-group col-md-3">
                @Html.LabelFor(model => model.StatusList, htmlAttributes: new { @class = "control-label" })
                <div class="col-md-12">
                    @Html.DropDownListFor(m => m.StatusID, Model.StatusList, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>

            <!--send method-->
            <div class="form-group col-md-3">
                @Html.LabelFor(model => model.SendMethodList, htmlAttributes: new { @class = "control-label" })
                <div class="col-md-12">
                    @Html.DropDownListFor(m => m.SentMethodID, Model.SendMethodList, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>

            <!--priority list-->
            <div class="form-group col-md-3">
                <label for="group_name" class="control-label">Priority</label>
                <div class="">
                    <select class="form-control" required>
                        <option>Normal</option>
                        <option>High</option>
                        <option>Low</option>
                    </select>
                </div>
            </div>
        </div>
        <!--heading-->
        <div class="form-group">
            @Html.LabelFor(model => model.NotificationHeading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NotificationHeading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NotificationHeading, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--description-->
        <div class="form-group">
            @Html.LabelFor(model => model.NotificationDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.NotificationDescription,  new { @class = "form-control"} )
                @Html.ValidationMessageFor(model => model.NotificationDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--start time-->
        <div class="form-group">
            @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
                @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--end time-->
        <div class="form-group">
            @Html.LabelFor(model => model.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDateTime, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
                @Html.ValidationMessageFor(model => model.EndDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create Thread" class="btn btn-success" />
                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

<script>
    $(document).ready(function () {
        $("#ServerList").change(function() {
            var serverRefIDs = $(this).val();
            $(".ApplicationListItem").hide();
            $.each(serverRefIDs, function (index, value) {
                $("." + value).show();
            });
        });
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval",
                    "~/bundles/summernote",
                    "~/Scripts/add-notification.js")
}

NotificationPortal/NotificationPortal/Views/Notification/Delete.cshtml
@model NotificationPortal.ViewModels.NotificationDetailVM

@{
    ViewBag.Title = "Delete Notification";
}

<h1 class="display-4 text-center pb-3">@ViewBag.Title - @Model.IncidentNumber</h1>

<ol class="breadcrumb bg-faded">
    <li class="breadcrumb-item"><a href="~/Dashboard/Index" class="link-color">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="~/Notification/Index" class="link-color">Notifications</a></li>
    <li class="breadcrumb-item active">Delete Notification</li>
</ol>

<dl class="row">
    <dt class="col-sm-2">@Html.DisplayNameFor(model => model.NotificationHeading)</dt>
    <dd class="col-sm-10">@Html.DisplayFor(model => model.NotificationHeading)</dd>

    <dt class="col-sm-2">@Html.DisplayNameFor(model => model.ReferenceID)</dt>
    <dd class="col-sm-10">@Html.DisplayFor(model => model.ReferenceID)</dd>

    <dt class="col-sm-2">@Html.DisplayNameFor(model => model.IncidentNumber)</dt>
    <dd class="col-sm-10">@Html.DisplayFor(model => model.IncidentNumber)</dd>

    <dt class="col-sm-2">@Html.DisplayNameFor(model => model.SentDateTime)</dt>
    <dd class="col-sm-10">@Html.DisplayFor(model => model.SentDateTime)</dd>

    <dt class="col-sm-2">@Html.DisplayNameFor(model => model.NotificationDescription)</dt>
    <dd class="col-sm-10">@Html.Raw(Model.NotificationDescription)</dd>
</dl>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @if (TempData["SuccessMsg"] != null)
        {
            <!-- display success message -->
            <p class="alert alert-success alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                @Html.Raw(TempData["SuccessMsg"])
            </p>
        }
        @if (TempData["ErrorMsg"] != null)
        {
            <!-- display error message -->
            <p class="alert alert-danger alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                @Html.Raw(TempData["ErrorMsg"])
            </p>
        }
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.NotificationHeading)
        @Html.HiddenFor(model => model.ReferenceID)
        @Html.HiddenFor(model => model.IncidentNumber)
        @Html.HiddenFor(model => model.SentDateTime)

        <div class="form-group">
            <div class="">
                <input type="submit" value="Delete Notification" class="btn btn-mint text-white" />
                @Html.ActionLink("Back", "DetailsThread", new { id = Model.IncidentNumber}, new { @class = "btn btn-danger" })

            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval",
                    "~/bundles/summernote",
                    "~/Scripts/add-notification.js")
}

NotificationPortal/NotificationPortal/Views/Notification/DetailsThread.cshtml
@model NotificationPortal.ViewModels.ThreadDetailVM

@{
    ViewBag.Title = "Notification Details";
}

<h1 class="display-4 text-center pb-3">@Model.IncidentNumber - @Model.Subject</h1>

<ol class="breadcrumb bg-faded">
    <li class="breadcrumb-item"><a href="~/Dashboard/Index" class="link-color">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="~/Notification/Index" class="link-color">Notifications</a></li>
    <li class="breadcrumb-item active">@Html.Raw(Model.IncidentNumber)</li>
</ol>

@if (TempData["SuccessMsg"] != null)
{
            <!-- display success message -->
    <p class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Html.Raw(TempData["SuccessMsg"])
    </p>
}
@if (TempData["ErrorMsg"] != null)
{
            <!-- display error message -->
    <p class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Html.Raw(TempData["ErrorMsg"])
    </p>
}
<!-- Nav tabs -->
<ul class="nav nav-tabs flex-xs-row" role="tablist">
    <li class="nav-item">
        <a class="nav-link flex-xs-fill text-sm-center active" data-toggle="tab" href="#Notifications" role="tab">Notifications</a>
    </li>
    @if (User.IsInRole(NotificationPortal.Models.Key.ROLE_ADMIN)
    || User.IsInRole(NotificationPortal.Models.Key.ROLE_STAFF))
    {
        <li class="nav-item">
            <a class="nav-link flex-xs-fill text-sm-center" data-toggle="tab" href="#Servers" role="tab">Servers</a>
        </li>
    }
    <li class="nav-item">
        <a class="nav-link flex-xs-fill text-sm-center" data-toggle="tab" href="#Applications" role="tab">Applications</a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <!-- Notifications Tab pane -->
    <div class="tab-pane active" id="Notifications" role="tabpanel">
    <h4>@Html.DisplayFor(model => model.Subject)</h4>
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.IncidentNumber)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.IncidentNumber)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.NotificationType)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.NotificationType)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.LevelOfImpact)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.LevelOfImpact)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Status)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Status)</dd>
        @if (User.IsInRole(NotificationPortal.Models.Key.ROLE_ADMIN) || User.IsInRole(NotificationPortal.Models.Key.ROLE_STAFF))
        {
            <dt class="col-sm-2">@Html.DisplayNameFor(model => model.SenderName)</dt>
                    <dd class="col-sm-10">@Html.DisplayFor(model => model.SenderName)</dd>
        }

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.StartDateTime)</dt>
        <dd class="col-sm-10">
            @if (Model.StartDateTime != null)
            {
                @Html.DisplayFor(model => model.StartDateTime)
            }
            else
            {
                @Html.Raw("TBA")
            }
        </dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.EndDateTime)</dt>
        <dd class="col-sm-10">
            @if (Model.EndDateTime != null)
            {

                @Html.DisplayFor(model => model.EndDateTime)
            }
            else
            {
                @Html.Raw("TBA")
            }
        </dd>
    </dl>
    <hr />
    <!-- list of threads-->
    <div class="row">
        @foreach (var item in Model.Thread)
        {
            var statusClass = "";
            switch (item.Status)
            {
                case NotificationPortal.Models.Key.STATUS_NOTIFICATION_CLOSED:
                    statusClass = "badge badge-grey";
                    break;
                case NotificationPortal.Models.Key.STATUS_NOTIFICATION_OPEN:
                    statusClass = "badge badge-red";
                    break;
                case NotificationPortal.Models.Key.STATUS_NOTIFICATION_INVESTIGATING:
                    statusClass = "badge badge-orange";
                    break;
                case NotificationPortal.Models.Key.STATUS_NOTIFICATION_RESOLVED:
                    statusClass = "badge badge-green";
                    break;
                default:
                    statusClass = "badge badge-grey";
                    break;
            }
            <div class="col-sm-12 single-thread">
                <span class="thread-status-bar">
                    @Html.Raw(item.SentDateTime)
                    <br />
                    <span class="@statusClass">@Html.Raw(item.Status)</span>
                    @if (User.IsInRole(NotificationPortal.Models.Key.ROLE_ADMIN) ||
                     User.IsInRole(NotificationPortal.Models.Key.ROLE_STAFF))
                    {
                        <a class="" href="@Url.Action("Edit", "Notification", new { id = @item.ReferenceID })">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </a>
                    }
                    @if (User.IsInRole(NotificationPortal.Models.Key.ROLE_ADMIN))
                    {
                        <a class="" href="@Url.Action("Delete", "Notification", new { id = @item.ReferenceID })">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                        </a>
                    }
                </span>

                <span class="thread-description">
                    <div class="card p-3 bg-light-grey font-small">
                        @Html.Raw(item.NotificationDescription)
                    </div>
                </span>
            </div>
        }
     </div>
        </div>
    
    @if (User.IsInRole(NotificationPortal.Models.Key.ROLE_ADMIN)
    || User.IsInRole(NotificationPortal.Models.Key.ROLE_STAFF))
    {
        <!-- Servers Tab pane -->
        <div class="tab-pane" id="Servers" role="tabpanel">
            <table class="table table-bordered">
                @{ var serverModel = Model.Servers.FirstOrDefault();}
                <thead>
                <tr class="bg-inverse text-white">
                    <th>
                        @Html.DisplayNameFor(model => serverModel.ServerName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => serverModel.ServerType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => serverModel.ServerStatus)
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.Servers)
                {
                    var serverStatusClass = item.ServerStatus.ToUpper() == NotificationPortal.Models.Key.STATUS_SERVER_OFFLINE.ToUpper()?"badge badge-danger": "badge badge-success";
                    <tr class="clickable-row" id="@item.ReferenceID" data-href="Server/Details/@item.ReferenceID">
                        <td data-title="@Html.DisplayNameFor(model => serverModel.ServerName)" class="first-row">
                            @Html.DisplayFor(modelItem => item.ServerName)
                        </td>
                        <td data-title="@Html.DisplayNameFor(model => serverModel.ServerType)">
                            @Html.DisplayFor(modelItem => item.ServerType)
                        </td>
                        <td data-title="@Html.DisplayNameFor(model => serverModel.ServerStatus)">
                            <span class="@serverStatusClass ml-1">
                                @Html.DisplayFor(modelItem => item.ServerStatus)
                            </span>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    }
    <!-- Applications Tab pane -->
    <div class="tab-pane" id="Applications" role="tabpanel">
        @if (Model.Applications.Count() == 0)
        {
            <p>There are no applications associated with this thread.</p>
        }
        else
        {
            var applicationModel = Model.Applications.FirstOrDefault();
            <table class="table table-bordered">
                <thead>
                <tr class="bg-inverse text-white">
                    <th>
                        @Html.DisplayNameFor(model => applicationModel.ApplicationName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => applicationModel.ApplicationURL)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => applicationModel.ApplicationStatus)
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.Applications)
                {
                    var appStatusClass = item.ApplicationStatus.ToUpper() == NotificationPortal.Models.Key.STATUS_APPLICATION_OFFLINE.ToUpper() ? "badge badge-danger" : "badge badge-success";
                    <tr class="clickable-row" id="@item.ReferenceID" data-href="Application/Details/@item.ReferenceID">
                        <td data-title="@Html.DisplayNameFor(model => applicationModel.ApplicationName)" class="first-row">
                            @Html.DisplayFor(modelItem => item.ApplicationName)
                        </td>
                        <td data-title="@Html.DisplayNameFor(model => applicationModel.ApplicationURL)">
                            @Html.DisplayFor(modelItem => item.ApplicationURL)
                        </td>
                        <td data-title="@Html.DisplayNameFor(model => applicationModel.ApplicationStatus)">
                            <span class="@appStatusClass">
                            @Html.DisplayFor(modelItem => item.ApplicationStatus)
                            </span>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        }
    </div>
</div>

<div>
    @if(User.IsInRole(NotificationPortal.Models.Key.ROLE_ADMIN)||
        User.IsInRole(NotificationPortal.Models.Key.ROLE_STAFF))
    {
        <!-- Create is only for internal users -->
        @Html.ActionLink("Update Thread", "Create", new { id = Model.IncidentNumber }, new { @class = "btn btn-mint text-white" })
    }
    @if (User.IsInRole(NotificationPortal.Models.Key.ROLE_ADMIN))
    {
        <!-- Only admin can delete threads -->
        @Html.ActionLink("Delete Thread", "DeleteThread", new { id = Model.IncidentNumber }, new { @class = "btn btn-danger" })
    }
</div>

<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>